select * from Employees;
select emp_name,salary from Employees;
select emp_name,department from Employees;
select * from Employees where department='IT';
select emp_name,experience from Employees;
select * from Employees where salary>70000;
select * from Employees where city='Hyderabad';
select * from Employees where experience<4;
select * from Employees where department='Finance';
select * from Employees where salary=52000;
select department,sum(salary) as total_salary from Employees group by department;
select department,avg(salary) as avg_salary from Employees group by department;
select city,count(*) as count_emp from Employees group by city;
select department,max(salary) as max_salary from Employees group by department;
select department,min(salary) as min_salary from Employees group by department;
select department,count(*) as count_emp from Employees group by department having count(*)>3;
select department,avg(salary) as avg_salary from Employees group by department having avg(salary)>60000;
select city,count(*) as count_emp from Employees group by city having count(*)>2;
select department,sum(salary) as total_salary from Employees group by department having sum(salary)>20000;
select department,max(salary) as max_salary from Employees group by department having max(salary)>90000;
select * from Employees order by salary desc limit 5;
select * from Employees order by experience desc limit 3;
select * from Employees where department = 'Finance' order by salary desc limit 2;
select emp_name from Employees where city = 'Hyderabad' limit 4;
select * from Employees order by salary desc limit 1;
select distinct department from Employees;
select distinct city from Employees;
select distinct salary from Employees;
select distinct department,city from Employees;
select distinct experience from Employees;
select * from Employees where salary>=80000;
select * from Employees where experience<=3;
select * from Employees where salary!=45000;
select * from Employees where salary<50000;
select * from Employees where experience>5;
select * from Employees where department = 'IT' and salary > 70000;
select * from Employees where city = 'Hyderabad' or city ='banglore';
select * from Employees where department = 'HR' and experience<3;
select * from Employees where experience>6 or salary > 60000;
select * from Employees where department != 'sales';
select * from Employees where city in ('Hyderabad', 'Mumbai');
select * from Employees where department in ('IT', 'Finance');
select * from Employees where city not in  ('Chennai', 'Pune');
select * from Employees where salary in (45000, 75000, 91000);
select * from Employees where department not in ('HR', 'Sales');
select * from Employees where salary between 50000 AND 80000;
select * from Employees where experience between 3 and 6;
select * from Employees where emp_id between 105 and 112;
select * from Employees where salary not between 40000 and 60000;
select * from Employees where experience between 2 and 4;
select * from Employees where emp_name like 'r%';
select * from Employees where emp_name like '%a';
select * from Employees where emp_name like '%v%';
select * from Employees where city like 'b%';
select * from Employees where department like '%s';